version: 2

builds:
  - binary: skill
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w
      - -X github.com/toba/skill/cmd.ver={{.Version}}
      - -X github.com/toba/skill/cmd.commit={{.ShortCommit}}
      - -X github.com/toba/skill/cmd.date={{.Date}}

archives:
  - formats:
      - tar.gz
    name_template: "{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}"
    format_overrides:
      - goos: windows
        formats:
          - zip

checksum:
  name_template: "checksums.txt"

changelog:
  sort: asc
  use: github
  filters:
    include:
      - "^feat"
      - "^fix"
      - "^perf"
      - "^refactor"
  groups:
    - title: Features
      regexp: "^feat"
      order: 1
    - title: Bug Fixes
      regexp: "^fix"
      order: 2
    - title: Performance
      regexp: "^perf"
      order: 3
    - title: Other
      order: 999

release:
  footer: >-

    ---

    Released by [GoReleaser](https://github.com/goreleaser/goreleaser).
