todo:
    path: .issues
    default_status: draft
    default_type: task
    sync:
        github:
            repo: toba/jig
companions:
    brew: https://github.com/toba/homebrew-jig.git
citations:
    - repo: hmans/beans
      branch: main
      notes: Original issue tracker source
      last_checked_sha: 0538bbcae06b493680ef156e80b4ecc68733fc85
      last_checked_date: "2026-02-24T17:10:02Z"
      paths:
        high:
            - '**/*.go'
        medium:
            - go.mod
            - go.sum
        low:
            - .github/**
            - README.md
            - LICENSE
    - repo: leegonzales/claude-guardrails
      branch: main
      notes: Nope alternative
      last_checked_sha: 931d277d228f59a95a3b03a0beab7beff5b74347
      last_checked_date: "2026-02-24T17:10:02Z"
      paths:
        high:
            - src/**/*.rs
        medium:
            - Cargo.toml
        low:
            - .github/**
            - README.md
            - LICENSE
