todo:
    path: .issues
    default_status: draft
    default_type: task
    sync:
        github:
            repo: toba/jig
companions:
    brew: https://github.com/toba/homebrew-jig.git
citations:
    - repo: hmans/beans
      branch: main
      notes: Original issue tracker source
      paths:
        high: ["**/*.go"]
        medium: [go.mod, go.sum]
        low: [".github/**", README.md, LICENSE]
    - repo: leegonzales/claude-guardrails
      branch: main
      notes: Nope alternative
      paths:
        high: ["src/**/*.rs"]
        medium: [Cargo.toml]
        low: [".github/**", README.md, LICENSE]
